### ISSUE TITLE
Bug: Deleting a chart having a suffix in its version via the API causes no removal from index

### ISSUE THREAD

**Issue by mahnkong** [kubernetes-helm/chartmuseum#22]
Hello,

We observed that deleting a chart having a suffix in its version via the API causes no removal from the index. The deletion from the file system works:

**POST, GET, DELETE for chart having a version without suffix:**
```
curl -X POST -k --data-binary "@mychart-1.0.4.tgz" localhost:8080/api/charts
{"saved":true}

curl localhost:8080/api/charts
{"mychart":[{"name":"mychart","version":"1.0.4","description":"mychart","apiVersion":"v1","urls":["charts/mychart-1.0.4.tgz"],"created":"2017-11-24T16:09:28.993494102+01:00","digest":"a4f08b5a9ccd5a958429c3ecf5fa45fdf2f271882cba7924c4fc9204645a8c7f"}]}

curl -X DELETE  localhost:8080/api/charts/mychart/1.0.4
{"deleted":true}

curl localhost:8080/api/charts
{}
```
**POST, GET, DELETE for chart having a version with suffix:**
```
curl -X POST -k --data-binary "@mychart-1.0.4-SNAPSHOT.tgz" localhost:8080/api/charts
{"saved":true}

curl localhost:8080/api/charts
{"mychart":[{"name":"mychart","version":"1.0.4-SNAPSHOT","description":"mychart","apiVersion":"v1","urls":["charts/mychart-1.0.4-SNAPSHOT.tgz"],"created":"2017-11-24T16:09:28.993494102+01:00","digest":"a4f08b5a9ccd5a958429c3ecf5fa45fdf2f271882cba7924c4fc9204645a8c7f"}]}

curl -X DELETE  localhost:8080/api/charts/mychart/1.0.4-SNAPSHOT
{"deleted":true}

curl localhost:8080/api/charts
{"mychart":[{"name":"mychart","version":"1.0.4-SNAPSHOT","description":"mychart","apiVersion":"v1","urls":["charts/mychart-1.0.4-SNAPSHOT.tgz"],"created":"2017-11-24T16:09:28.993494102+01:00","digest":"a4f08b5a9ccd5a958429c3ecf5fa45fdf2f271882cba7924c4fc9204645a8c7f"}]}
```

Best regards,
Andreas

**Comment by jdolitsky** [comment]
Thanks for detailed report, will look into this shortly

**Comment by jdolitsky** [comment]
I believe the bug is in how the chart version is determined here:
https://github.com/kubernetes-helm/chartmuseum/blob/master/pkg/repo/chart.go#L76

It's splitting by "-", then taking last item of the slice, so version in this case would be "SNAPSHOT" vs. "1.0.4-SNAPSHOT". I'm interested to know if this bug exists if you try using version wihtout an additonal hyphen (1.0.4SNAPSHOT)

**Comment by jdolitsky** [comment]
@mahnkong This should fixed in the latest build. Please let us know if you have any issues. Thanks!

**Comment by cfontes** [comment]
Still happens today

**Comment by ahmadalli** [comment]
I'm having issue with deleting chart with simple version number. this is my chart:

```json
{
  "name": "chart",
  //...
  "version": "5.0.14",
  //...
}
```

and when I try to `curl -X Delete $CHARTMUSEUM_URL/api/cache/charts/chart/5.0.14` I get `{"error":"not found"}` while `curl -X Delete $CHARTMUSEUM_URL/api/cache/charts/chart | jq -r '.[].version' returns the `5.0.14` version

**Comment by digitalassembly** [comment]
It still happens in the latest version, my version is something like 1.0.0-rc1, deleting using CURL doesn't delete from index.

**Comment by scbizu** [comment]
> I'm having issue with deleting chart with simple version number. this is my chart:
> 
> ```json
> {
>   "name": "chart",
>   //...
>   "version": "5.0.14",
>   //...
> }
> ```
> 
> and when I try to `curl -X Delete $CHARTMUSEUM_URL/api/cache/charts/chart/5.0.14` I get `{"error":"not found"}` while `curl $CHARTMUSEUM_URL/api/cache/charts/chart | jq -r '.[].version' returns the `5.0.14` version

@ahmadalli  Hihi, can you provide the whole bootstrap command , It seems strange that why you delete the chart via `/cache/charts/` ?

**Comment by scbizu** [comment]
@digitalassembly Can you provide more details ? I tried but it can delete correctly. Here is what I tried .

```shell
$ helm package testdata/charts/mychart
Successfully packaged chart and saved it to: /Users/scnace/Projects/scnace/chartmuseum/mychart-0.0.1-rc1.tgz

$ curl --data-binary "@mychart-0.0.1-rc1.tgz" http://localhost:8080/api/charts
{"saved":true}

$ curl -X DELETE  http://localhost:8080/api/charts/mychart/0.0.1-rc1
{"deleted":true}

$ cat .storage/index-cache.yaml

apiVersion: v1
entries:
  mychart:
  - apiVersion: v1
    created: "2020-05-20T01:22:26.8099537+08:00"
    digest: f0ac3a5a21c0cc5cea872b53829f8c401adfb1e2e7cd57eb19cc75e20cfb4859
    name: mychart
    urls:
    - charts/mychart-0.1.0.tgz
    version: 0.1.0
  - apiVersion: v1
    created: "2020-05-20T01:24:52.653080549+08:00"
    digest: f4803128e58eb5f518cdc79b898b08cd975f262decf371f8682df2d9dcf673ec
    name: mychart
    urls:
    - charts/mychart-0.1.0+1.foo.tgz
    version: 0.1.0+1.foo
generated: "2020-06-26T16:19:34+08:00"
serverInfo: {}

```

**Comment by ahmadalli** [comment]
@scbizu sorry I don't have time to reproduce the issue now. `/cache/` is one of the tenants

**Comment by pixelicous** [comment]
Not sure why this is closed, this clearly still happens, to us as well, the fact that we get deleted true on charts that do not exist is also a red flag
